Repository zammad/zammad-admin-documentation, pull requests merged in 2023-03, with the labels that each got.

#215 Add remark about data privacy storage retention to FAQ
  locale/admin-docs.pot
  system/data-privacy.rst
Labels: enhancement, next release

#200 Extend SAML Keycloak configuration
  settings/security/third-party/saml.rst
Labels: needs verification

#217 Zammad 5.4
  _static/theme/mermaid.min.js
  _static/theme/theme_overrides.css
  conf.py
  images/icons/subclause-64px.png
  images/manage/templates/adding-new-template.png
  images/misc/object-conditions/adding-conditions-to-blocks.gif
  images/misc/object-conditions/adding-logic-blocks.gif
  images/misc/object-conditions/enable_expert-mode.gif
  images/misc/object-conditions/follow-up-message-details.gif
  images/misc/object-conditions/re-arranging-conditions.gif
  images/settings/security/account-linking-notification-sample.png
  images/settings/security/automatic-account-link-notification.png
  index.rst
  locale/admin-docs.pot
  locale/de/LC_MESSAGES/admin-docs.po
  locale/es/LC_MESSAGES/admin-docs.po
  locale/fr/LC_MESSAGES/admin-docs.po
  locale/fr_CA/LC_MESSAGES/admin-docs.po
  locale/hr/LC_MESSAGES/admin-docs.po
  locale/it/LC_MESSAGES/admin-docs.po
  locale/pt_BR/LC_MESSAGES/admin-docs.po
  locale/ru/LC_MESSAGES/admin-docs.po
  locale/th/LC_MESSAGES/admin-docs.po
  locale/tr/LC_MESSAGES/admin-docs.po
  locale/zh_Hans/LC_MESSAGES/admin-docs.po
  manage/overviews.rst
  manage/report-profiles.rst
  manage/scheduler.rst
  manage/slas/how-do-they-work.rst
  manage/templates.rst
  manage/time-accounting.rst
  manage/trigger/how-do-they-work.rst
  manage/trigger/limitations.rst
  manage/trigger/system-notifications.rst
  misc/object-conditions/basics.rst
  misc/object-conditions/conditioning-depth-hint.include.rst
  misc/object-conditions/datetime-conditions.include.rst
  misc/object-conditions/expert-mode.rst
  misc/object-conditions/index.rst
  misc/object-conditions/time-conditions-mermaid.include.rst
  requirements.txt
  settings/security/third-party.rst
  settings/security/third-party/saml.rst
  settings/ticket.rst
  system/data-privacy.rst
Labels: next release
